import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const __dirname = dirname(fileURLToPath(import.meta.url))
const schemaPath = resolve(__dirname, 'openapi.json')
const outPath = resolve(__dirname, 'src/index.ts')

const ast = await openapiTS(new URL(`file://${schemaPath}`))
const banner = `// THIS FILE IS AUTO-GENERATED BY openapi-typescript. DO NOT EDIT.\n\n`

await mkdir(dirname(outPath), { recursive: true })
await writeFile(outPath, banner + astToString(ast), 'utf8')
console.log(`wrote ${outPath}`)
